name: ci

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get tag version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -o '[^/]*$')
        env:
          tag_name: ${{ tag_name }}

      - name: out tag version
        run: |
          echo "The tag name is $tag_name"
