name: ci

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get tag version
        id: step_one
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -o '[^/]*$')
          echo "::set-output name=tag_name::$tag_name"

      - name: out tag version
        run: |
          echo ${{ steps.step_one.outputs.tag_name }}
